<a href="https://colab.research.google.com/github/armahin/Numpy/blob/main/1.%20Numpy%20Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are **all required to be of the same data type**, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

###**1. Creating Numpy Arrays**

*Functions*

**np.array**

In [4]:
# np.array
import numpy as np
# To create a numpy array we just need to pass a list to the method np.array()
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
#2D and 3D Numpy Array
b = np.array([[1,2,3],[2,5,4]])
print(b)
print()
c = np.array([[1,2,3],[2,5,4],[4,5,1]])
print(c)

[[1 2 3]
 [2 5 4]]

[[1 2 3]
 [2 5 4]
 [4 5 1]]


1D -> Vector

2D -> Matrix

3d -> Tensor

In [13]:
# dtype
# If we want we can create our own data typed numpy array
np.array([1,2,3],dtype = float)
np.array([1,2,3],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

**np.arange**

In [18]:
# np.arange
# It works line the range function
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**np.arange().reshape()**

In [20]:
# with reshape - It changes the shape
np.arange(1,11).reshape(5,2)
# Obviously it will work only when it's possible so the two numbers product will have to be equal to the number of elements in the array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

**np.ones & np.zeros**

In [21]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**np.random**

In [23]:
# np.random
np.random.random((3,4))

array([[0.35874191, 0.57405689, 0.14016702, 0.80323693],
       [0.02461908, 0.14831823, 0.9531983 , 0.92553112],
       [0.37676919, 0.54489061, 0.09396613, 0.14699503]])

**np.linspace**

In [26]:
# np.linspace - linearly spaced
# it says to give 10 numbers from -10 to 10
# Distance between two points are equal
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

**np.identity**

In [27]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### **2. Array Attributes**

In [34]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

**ndim - means number of dimensions**

In [36]:
#ndim
a2.ndim

2

**shape - rows and columns**

In [38]:
a2.shape

(3, 4)

**size - number of items**

In [39]:
a3.shape

(2, 2, 2)

**itemsize - how much memory is occupied by per item**

In [42]:
a2.itemsize

8

**dtype = it says what it the datatype of the item**

In [44]:
a3.dtype

dtype('int64')

### **3. Changing Datatype**

In [47]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### **4. Array Operations**

In [50]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**Two Types of operations can be happend**

1. Scalar
2. Vector

In [53]:
# 1. Scalar Operations
#Arithmatic
print(a1 * 2)
print()
print(a1 + 4)
print()
print(a1 / 3)
print()
print(a1 % 2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[0.         0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.         2.33333333]
 [2.66666667 3.         3.33333333 3.66666667]]

[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [55]:
#Relational
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [56]:
# Vector Operations -> Whenever we operate on two numpy arrays
a1 * a2


array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

###**5. Array Functions**

In [57]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[16., 38., 46.],
       [20., 85., 20.],
       [ 2.,  9., 69.]])

In [61]:
# max/min/sum/prod
# 0 -> col and 1 -> row
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

# To get the min or max in columns or rows
print(np.min(a1,axis=0)) # In column
print(np.min(a1,axis=1)) # In Rows

85.0
2.0
305.0
1181032704000.0
[ 2.  9. 20.]
[16. 20.  2.]


In [62]:
# mean/median/std/var
np.mean(a1)
np.median(a1)
np.std(a1)
np.var(a1)

705.6543209876543

In [63]:
# trigonomoetric functions
np.sin(a1)

array([[-0.28790332,  0.29636858,  0.90178835],
       [ 0.91294525, -0.17607562,  0.91294525],
       [ 0.90929743,  0.41211849, -0.11478481]])

In [73]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
print(a2)
print(a3)
np.dot(a2,a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [75]:
# log and exponents
np.log(a1)
np.exp(a1)

array([[2.77258872, 3.63758616, 3.8286414 ],
       [2.99573227, 4.44265126, 2.99573227],
       [0.69314718, 2.19722458, 4.2341065 ]])

In [80]:
# round/floor/ceil
np.round(np.random.random((2,3))*100) # Rounds off
np.floor(np.random.random((2,3))*100) # if 6.9 then it takes 6
np.ceil(np.random.random((2,3))*100) # if 6.1 it takes 7

array([[49., 74., 28.],
       [42., 29., 32.]])

### **6. Indexing and Slicing**

In [85]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


**Indexing**

In [87]:
#Let's take a1
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
#Suppose somebody is telling me to bring out the last item or first
a1[-1]
a1[0]

0

In [90]:
#Let's take 2D array
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#Let's say i have to take out the 6


In [95]:
a2[1,2]

6

In [92]:
#Let's take 3D array
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [97]:
a3[1,0,1]

5

**Slicing**

With the help of indexing, we could just bring out one item but with slicing **we can take out multiple items if we want**

In [98]:
# 1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
# Let's bring out 2,3,4
a1[2:5]

array([2, 3, 4])

In [101]:
# 2D
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
# Let's bring out the first row
a2[0,:]

array([0, 1, 2, 3])

In [106]:
# Let's bring out the third column
a2[:,2]

array([ 2,  6, 10])

In [109]:
# Let's bring out 5,6,9,10
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [110]:
# Let's bring out 0,3,8,11
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [111]:
# Let's bring out 1,3,9,11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [120]:
# Let's bring out 4,7
a2[1,0::3]

array([4, 7])

In [123]:
# 3D
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [124]:
# Let's bring out the mid matrix
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [126]:
# Let's bring out the first and last matrix
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [131]:
# Let's bring out the first 2D array's 2nd Row [3,4,5]
a3[0,1,:]

array([3, 4, 5])

In [132]:
# Let's bring out the 2nd 2D array's 2nd Column [10,13,16]
a3[1,:,1]

array([10, 13, 16])

In [133]:
# Let's bring out the 3rd 2D array's 22,23,25,26
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [140]:
# Let's bring out the 0,2,18,20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### **7. Iterating**

In [141]:
# If you want you can loop on your numpy arrays
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [144]:
#Looping on these 3 arrays

In [145]:
#1D
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [148]:
#2D
# If we iterate through 2D then one row is printed per session
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [151]:
#3D
# 2D array will be printed per session
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [153]:
#if we want to loop through 2D and 3D items
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### **8. Reshaping**

In [ ]:
#reshape

In [155]:
#transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [157]:
#ravel -> Turn any dimensional matrix into 1D
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### **9. Stacking**
Concatinating two or more arrays

In [162]:
#horizontal stacking ->
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [163]:
#vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### **10. Splitting**

In [164]:
#horizontal splitting ->
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [166]:
#vertical splitting ->
a7 = np.arange(36).reshape(4,9)
np.vsplit(a7,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]])]