<a href="https://colab.research.google.com/github/armahin/Numpy/blob/main/3.%20Numpy%20Tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## np.sort

Returns a sorted copy of an array

In [ ]:
#Code
import numpy as np
a = np.random.randint(1,100,15)
print(a)
print(np.sort(a))
print('To sort this in descending order')
print(np.sort(a)[::-1])

[49 29 13 20 43 83 96  8 76 84 11 35 32 88 61]
[ 8 11 13 20 29 32 35 43 49 61 76 83 84 88 96]
To sort this in descending order
[96 88 84 83 76 61 49 43 35 32 29 20 13 11  8]


In [ ]:
b = np.random.randint(1,100,15).reshape(5,3)
print(b)
print('This will be sorted in column wise')
print(np.sort(b,axis = 0))
print('This will be sorted in row wise')
print(np.sort(b,axis = 1))

[[ 7 48 24]
 [71 55 16]
 [28 49  8]
 [50 89 16]
 [24 16 21]]
This will be sorted in column wise
[[ 7 16  8]
 [24 48 16]
 [28 49 16]
 [50 55 21]
 [71 89 24]]
This will be sorted in row wise
[[ 7 24 48]
 [16 55 71]
 [ 8 28 49]
 [16 50 89]
 [16 21 24]]


## np.append

Appends values along the mentioned axis at the end of the array

In [ ]:
print(a)

[49 29 13 20 43 83 96  8 76 84 11 35 32 88 61]


In [ ]:
np.append(a,200)

array([ 49,  29,  13,  20,  43,  83,  96,   8,  76,  84,  11,  35,  32,
        88,  61, 200])

In [ ]:
print(b)

[[ 7 48 24]
 [71 55 16]
 [28 49  8]
 [50 89 16]
 [24 16 21]]


In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[ 7., 48., 24.,  1.],
       [71., 55., 16.,  1.],
       [28., 49.,  8.,  1.],
       [50., 89., 16.,  1.],
       [24., 16., 21.,  1.]])

## np.concatinate

Concatinates a sequence of arrays along an existing axis.

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## np.unique

gets the unique value from a given array

In [ ]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

## np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

Ex: if we have 1D array we can convert it to 2D array

In [ ]:
a

array([49, 29, 13, 20, 43, 83, 96,  8, 76, 84, 11, 35, 32, 88, 61])

In [ ]:
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis = 0)

array([[49, 29, 13, 20, 43, 83, 96,  8, 76, 84, 11, 35, 32, 88, 61]])

In [ ]:
np.expand_dims(a,axis = 0).shape

(1, 15)

## np.where

returns the indices of elements in an input array where the given condition is satisfied.



In [ ]:
a

array([49, 29, 13, 20, 43, 83, 96,  8, 76, 84, 11, 35, 32, 88, 61])

In [ ]:
#Find all indices with value greater than 50
np.where(a>59)

(array([ 5,  6,  8,  9, 13, 14]),)

In [ ]:
#Replace all values > 50 with 0
# np.where(condition,what to do when true,what to do when false)
np.where(a>50,0,a)

array([49, 29, 13, 20, 43,  0,  0,  8,  0,  0, 11, 35, 32,  0,  0])

In [ ]:
# Replace all even numbers with 0
np.where(a%2 == 0,0,a)

array([49, 29, 13,  0, 43, 83,  0,  0,  0,  0, 11, 35,  0,  0, 61])

## np.argmax

Rreturns indices of the max element of the array in a particular axis.


In [ ]:
a

array([49, 29, 13, 20, 43, 83, 96,  8, 76, 84, 11, 35, 32, 88, 61])

In [ ]:
np.argmax(a)

6

In [ ]:
b

array([[ 7, 48, 24],
       [71, 55, 16],
       [28, 49,  8],
       [50, 89, 16],
       [24, 16, 21]])

In [ ]:
np.argmax(b,axis = 0) #Column

array([1, 3, 0])

In [ ]:
np.argmax(b,axis = 1) #Row

array([1, 0, 1, 1, 0])

In [ ]:
# np.argmin does the opposite

## np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.


In [ ]:
a

array([49, 29, 13, 20, 43, 83, 96,  8, 76, 84, 11, 35, 32, 88, 61])

In [ ]:
np.cumsum(a)

array([ 49,  78,  91, 111, 154, 237, 333, 341, 417, 501, 512, 547, 579,
       667, 728])

In [ ]:
b

array([[ 7, 48, 24],
       [71, 55, 16],
       [28, 49,  8],
       [50, 89, 16],
       [24, 16, 21]])

In [ ]:
np.cumsum(b,axis = 0)

array([[  7,  48,  24],
       [ 78, 103,  40],
       [106, 152,  48],
       [156, 241,  64],
       [180, 257,  85]])

In [ ]:
#np.cumprod
np.cumprod(a)

array([                  49,                 1421,                18473,
                     369460,             15886780,           1318602740,
               126585863040,        1012686904320,       76964204728320,
           6464993197178880,    71114925168967680,  2489022380913868800,
        5861739894405595136,  -675723356175073280, -4325636579260366848])

## np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.


In [ ]:
a

array([49, 29, 13, 20, 43, 83, 96,  8, 76, 84, 11, 35, 32, 88, 61])

In [ ]:
np.percentile(a,50)

43.0

In [ ]:
np.median(a)

43.0

## np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [ ]:
a

array([49, 29, 13, 20, 43, 83, 96,  8, 76, 84, 11, 35, 32, 88, 61])

In [ ]:
np.histogram(a , bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 2, 2, 2, 0, 1, 1, 3, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

## np.corrcoef

Return Pearson product-moment correlation coefficients.

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [ ]:
a

array([49, 29, 13, 20, 43, 83, 96,  8, 76, 84, 11, 35, 32, 88, 61])

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]

np.isin(a,items)

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
a[np.isin(a,items)]

array([20])

## np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [ ]:
a

array([49, 29, 13, 20, 43, 83, 96,  8, 76, 84, 11, 35, 32, 88, 61])

In [ ]:
np.flip(a)

array([61, 88, 32, 35, 11, 84, 76,  8, 96, 83, 43, 20, 13, 29, 49])

## np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.


In [ ]:
a

array([49, 29, 13, 20, 43, 83, 96,  8, 76, 84, 11, 35, 32, 88, 61])

In [ ]:
# np.put(array,where to change,with what to change)
np.put(a,[0,1],[110,530])

## np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [ ]:
a

array([110, 530,  13,  20,  43,  83,  96,   8,  76,  84,  11,  35,  32,
        88,  61])

In [ ]:
np.delete(a,[0,2,4])

array([530,  20,  83,  96,   8,  76,  84,  11,  35,  32,  88,  61])

## Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [ ]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(m,n) # That has in m but not in n

array([1, 2])

In [ ]:
np.setxor1d(m,n) # Common will be dropeed

array([1, 2, 6, 7])

In [ ]:
np.in1d(m,n) #Acts like membership operator which is, if in m, n is available or not

array([False, False,  True,  True,  True])

## np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

In [ ]:
a

array([110, 530,  13,  20,  43,  83,  96,   8,  76,  84,  11,  35,  32,
        88,  61])

In [ ]:
np.clip(a,a_min = 25,a_max = 75)

array([75, 75, 25, 25, 43, 75, 75, 25, 75, 75, 25, 35, 32, 75, 61])